### ISSUE TITLE
SSH Host Key Fingerprint

### ISSUE THREAD

**Issue by DouglasMarcelinoDev** [sshnet/SSH.NET#835] opened 2021-06-10 20:38 UTC
Using WinSCP DLL, I can configure my ssh host key fingerprint like this

SessionOptions sessionOptions = new SessionOptions
            {
                Protocol = Protocol.Sftp,
                HostName = config.Host,
                UserName = config.User,
                PortNumber = config.Port,
                Password = config.Password,
                SshHostKeyFingerprint = config.Key
            };
    
 where config.Key = "ssh-rsa 2048 [...]="
 
 How can I add this "SshHostKeyFingerprint" using SSH.NET dll?
 
 something like that 
 
 client = new SftpClient(config.Host, config.Port, config.User, config.Password, config.Key);

**Comment by IgorMilavec** [comment] 2021-06-14 15:19
You need to attach to the ```HostKeyReceived``` event before establishing the connection:
```C#
var client = new SftpClient(connectionInfo);
client.HostKeyReceived += (sender, e) =>
{
    // e is an Renci.SshNet.Common.HostKeyEventArgs that you can use to check the received host key
    // throw here to abort the connection
};
client.Connect();
```

**Comment by DouglasMarcelinoDev** [comment] 2021-06-15 16:15
@IgorMilavec Well, when I try this, I get this error
Accessing a hash algorithm by manipulating the HashName property is not supported on this platform. Instead, you must instantiate one of the supplied subtypes (such as HMACSHA1.)

```cs
var client = new SftpClient(config.Host, config.Port, config.User, config.Password);
client.HostKeyReceived += (sender, e) =>
{

     e.CanTrust = true;

};

client.Connect();

```

Where I can attach config.Key = "ssh-rsa 2048 [...]="?

**Comment by IgorMilavec** [comment] 2021-06-17 16:53
You can not (AFAIK) "attach" the key, you must validate it inside HostKeyReceived event handler. Something like this:

```C#
var client = new SftpClient(config.Host, config.Port, config.User, config.Password);
client.HostKeyReceived += (sender, e) =>
{
     e.CanTrust = (FormatKey(e) == config.Key);
};

client.Connect();
```
Of course you need to implement ```FormatKey``` function appropriately.

**Comment by IgorMilavec** [comment] 2022-03-23 19:40
@DouglasMarcelinoDev this is a duplicate of #859 , please see a workaround there.

**Closed as completed by IgorMilavec** 2022-03-23 19:40 UTC
