### ISSUE TITLE
Download of large files hangs intermittently, then resumes, prolonging download times drastically

### ISSUE THREAD

**Issue by k5123** [sshnet/SSH.NET#849] opened 2021-07-15 19:22 UTC
Whenever i download a large file (1GB+) i see the download stopping intermittently, for a couple of minutes, then the download resumes. This obviously prolongs the download times dramatically.

**Comment by drieseng** [comment] 2021-07-15 19:27
Duplicate of #733.

**Closed as completed by drieseng** 2021-07-15 19:27 UTC
