### ISSUE TITLE
An established connection was aborted by the server. (SOCKS5 Proxy)

### ISSUE THREAD

**Issue by HarbourFrieght2** [sshnet/SSH.NET#633] opened 2020-02-28 09:36 UTC
`var connectionInfo = new ConnectionInfo("a.host.name", 22, username, ProxyTypes.Socks5, "127.0.0.1", 9050, "", "",
                        new PasswordAuthenticationMethod(username, password)
                        );`

Results in the following exception. I can use the specified proxy in putty, firefox, other applications etc just fine, however it is not working with SSH.NET 

> Unhandled Exception: Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server.
   at Renci.SshNet.Abstractions.SocketAbstraction.Send(Socket socket, Byte[] data, Int32 offset, Int32 size)
   at Renci.SshNet.Session.ConnectSocks5()
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at WS.Program.Main(String[] args)

If I try to use localhost instead of 127.0.0.1, the following different exception is thrown

> Unhandled Exception: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at WS.Program.Main(String[] args)

**Comment by drieseng** [comment] 2020-06-28 06:17
This is probably a duplicate of issue #125.
Please try [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1), and reopen this issue if that didn't resolve the problem for you.

**Closed as completed by drieseng** 2020-06-28 06:17 UTC
