### ISSUE TITLE
Problem with some SFTP server which send only linefeed and not linefeed with carriagereturn

### ISSUE THREAD

**Issue by nlubac** [sshnet/SSH.NET#768] opened 2021-01-20 15:39 UTC
I have found a problem if I want to connect to an SFTP (with linux OS) which send only a linefeed and not linefeed with carriagereturn.

I have modify HttpConnector and ProtocolVersionExchange in order to manage the both possibility of the linefeed.

I hope you can make a new version with this feature.

**Comment by drieseng** [comment] 2021-01-20 19:36
This is a duplicate of issue #761. I'll try to find time to release a fix asap.

**Closed as completed by drieseng** 2021-01-20 19:36 UTC

**Comment by nlubac** [comment] 2021-01-21 09:22
For information, I have make this modification (and it's run on both possiblity of LF or CRLF).

                if (byteRead == Session.LineFeed && buffer.Count > startPosition + 1)
                {
                    // Return current line without CRLF
                    return Encoding.UTF8.GetString(buffer.ToArray(), startPosition, buffer.Count - (startPosition + 1 + (buffer[buffer.Count - 2] == Session.CarriageReturn ? 1 : 0)));
                }

Have a good day.

**Comment by drieseng** [comment] 2021-01-24 14:19
Release [2020.0.1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.1) is now available.
