### ISSUE TITLE
Changing ClientAliveInterval and ClientAliveCountMax values in sshd_config file causes unexpected exceptions

### ISSUE THREAD

**Issue by mauroa** [sshnet/SSH.NET#105] opened 2016-10-26 19:55 UTC
If I uncomment the ClientAliveInterval and ClientAliveCountMax values of the sshd_config file in a Mac and I try to connect with SshClient and ScpClient and try to upload files, then unexpected exception occurs.

Note that If I comment the values again, then everything works as expected. Find below the stack traces of the exceptions:

System.NotSupportedException: Data longer than 2147483647 is not supported.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Channels.ChannelSession.Open()
   at Renci.SshNet.ScpClient.Upload(Stream source, String path)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Renci.SshNet.Common.SshDataStream.ReadBytes(Int32 length)
   at Renci.SshNet.Common.SshDataStream.ReadBinary()
   at Renci.SshNet.Messages.Connection.GlobalRequestMessage.LoadData()
   at Renci.SshNet.Session.LoadMessage(Byte[] data, Int32 offset)
   at Renci.SshNet.Session.ReceiveMessage()
   at Renci.SshNet.Session.MessageListener()

**Comment by drieseng** [comment] 2016-10-27 18:07
What are the values of those settings ?
Can you also reproduce this issue using a Linux OpenSSH server?

**Comment by drieseng** [comment] 2016-11-02 20:29
@mauroa Ping!

**Comment by mauroa** [comment] 2016-11-10 17:20
Sorry for the delay. I have only tried on macOS by now. The values of the sshd_config are the deault ones on that file for a Mac:

ClientAliveInterval 3
ClientAliveCountMax 5

**Comment by drieseng** [comment] 2016-11-27 16:13
I can't reproduce this. Do you have a system available that I could test against?

**Comment by drieseng** [comment] 2016-12-16 09:24
This appears to be a duplicate of issue #58, which is fixed in **2016.1.0-beta1**.
Please try using that version, and reopen this issue if you can still reproduce the problem.

**Closed as completed by drieseng** 2016-12-16 09:24 UTC
Labels: duplicate
