### ISSUE TITLE
The server response contains a null character at position 

### ISSUE THREAD

**Issue by gabrielfarias93** [sshnet/SSH.NET#769] opened 2021-01-21 14:00 UTC
I'm trying to access a freeradius server for ssh COA and i'm receiving follow error:

Renci.SshNet.Common.SshConnectionException: 'The server response contains a null character at position 0x00000028:

  00000000  53 53 48 2D 32 2E 30 2D 4F 70 65 6E 53 53 48 5F  SSH-2.0-OpenSSH_
  00000010  37 2E 34 70 31 20 44 65 62 69 61 6E 2D 31 30 2B  7.4p1 Debian-10+
  00000020  64 65 62 39 75 36 0A 00                          deb9u6..

A server must not send a null character before the Protocol Version Exchange is complete.

More information is available here:
https://tools.ietf.org/html/rfc4253#section-4.2'

What can i do?

**Comment by drieseng** [comment] 2021-01-23 18:54
This is a duplicate of issue #761. I hope to be able to release 2020.0.1 tomorrow.

**Closed as completed by drieseng** 2021-01-23 18:54 UTC

**Comment by gabrielfarias93** [comment] 2021-01-23 18:56
> This is a duplicate of issue #761. I hope to be able to release 2020.0.1 tomorrow.

Thanks dude

**Comment by drieseng** [comment] 2021-01-24 14:10
Release [2020.0.1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.1) is now available.
