### ISSUE TITLE
SftpClient Handle leak (even when connection is successful)

### ISSUE THREAD

**Issue by lahsrah** [sshnet/SSH.NET#223] opened 2017-05-18 01:43 UTC
This is my entire code (using SSH.NET 2016.0.0 from nuget and .net 4.6.2 console app)

```
class Program
    {
        static void Main(string[] args)
        {
            int count = 0;

            while (true)
            {
                using (SftpClient client = new SftpClient("127.0.0.1", 22, "Username", "Password"))
                {
                    client.Connect();
                    var dir = client.ListDirectory("/");
                   
                    client.Disconnect();
                }

                if (++count % 100 == 0)
                {
                    Thread.Sleep(2000);
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    GC.Collect();

                    Console.WriteLine("Collected at " + count);
                }
            }
        }
    }
```

After 12000 connections and disconnection my process is sitting at 25MB Memory usage but 12,238 Handles.   What am i doing wrong?

I am running this in release mode and even forcing Garbage Collection every 100 connections just in case GC wasn't kicking in. 

If you want a tiny self contained ftp server to test it with locally, I am using this: http://labs.rebex.net/tiny-sftp-server

I have already looked at this and it doesn't seem to be the same : https://github.com/sshnet/SSH.NET/issues/87

EDIT: It looks like this has been fixed in 2016.1.0-Beta1

**Comment by drieseng** [comment] 2017-07-21 12:40
This is indeed a duplicate of issue #87 and/or #133.
Please try using version **2016.1.0-beta1** or the upcoming **2016.1.0-beta2** release.

**Closed as completed by drieseng** 2017-07-21 12:40 UTC
Labels: duplicate
