### ISSUE TITLE
port forwarding not allowed

### ISSUE THREAD

**Issue by maxmontgmx** [sshnet/SSH.NET#1058] opened 2022-12-06 13:38 UTC
Hi all,

When we make local port forwarding, doe it exit a way to know if the port forwarding is allow by the remote host?
In my case I case port forwarding without error although port forwarding is prohibited on the remote host.

Thanks for your help

**Comment by maxmontgmx** [comment] 2022-12-13 16:14
Hi all,
No response, no help.
Please
Thanks in advance...

**Comment by WojciechNagorski** [comment] 2023-08-25 12:30
I am closing the issue due to lack of time and the report does not contain enough information to reproduce the bug.

**Comment by WojciechNagorski** [comment] 2023-08-25 12:30
@maxmontgmx This is an open source project and we spend our free time solving the issue.

**Closed as completed by WojciechNagorski** 2023-08-25 12:30 UTC
