### ISSUE TITLE
Cannot mock sftpClient.connect() method

### ISSUE THREAD

**Issue by praveensankar969** [sshnet/SSH.NET#920] opened 2022-02-18 05:16 UTC
Unable to mock SftpClient's BaseClient.Connect() method. 
No interface for Renci.SshNet.BaseClient class

**Comment by IgorMilavec** [comment] 2022-02-19 10:35
Please explain your use case in more detail. I this a duplicate of #890 or at least so similar that it could be discussed as part of it? If yes, then please close this issue and move the discussion to #890.

**Closed as completed** 2022-02-20 06:10 UTC
