### ISSUE TITLE
.Net Core 2.0 Support?

### ISSUE THREAD

**Issue by Dawandevo** [sshnet/SSH.NET#436] opened 2018-05-24 14:56 UTC
When will the project get support for .net core 2.0?

currently the project is unusable with other up to date libraries.

**Comment by ScottRFrost** [comment] 2018-06-02 16:27
Duplicate of #377 and #413

**Comment by drieseng** [comment] 2018-07-26 19:30
.NET Core 2.0 is supported through our .NET Standard 2.0 assembly.
I'll be releasing a new beta for it soon.

**Comment by mrtylerzhou** [comment] 2019-03-03 02:49
@drieseng any news on the beta with .Net Standard 2.0 support?

**Comment by krugertech** [comment] 2019-07-10 10:16
> .NET Core 2.0 is supported through our .NET Standard 2.0 assembly.
> I'll be releasing a new beta for it soon.

Hi @drieseng 

Have you released the new beta yet ?

**Comment by Mgamerz** [comment] 2019-12-28 19:02
I would much appreciate a new beta. I am using .net core 3 and this has many extra dependencies that are not present if using .net standard 2.

**Closed as completed** 2020-04-26 09:34 UTC
