### ISSUE TITLE
cipher name aes256-ctr for openssh key file is not supported

### ISSUE THREAD

**Issue by AndreMarschalek** [sshnet/SSH.NET#898] opened 2021-11-16 19:44 UTC
also mentioned @ https://github.com/sshnet/SSH.NET/issues/742 but still existing with 2020.0.1

Renci.SshNet.PrivateKeyFile.ParseOpenSshV1Key(byte[] keyFileData, string passPhrase)
Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, string passPhrase)
Renci.SshNet.PrivateKeyFile..ctor(string fileName, string passPhrase)

**Comment by IgorMilavec** [comment] 2022-02-13 00:23
Am I correct to understand this is a duplicate of #742? If yes, can you please close this issue?

**Closed as completed** 2022-02-14 21:45 UTC
