### ISSUE TITLE
SSH.NET Unit Testing framework Causing Virus Issues

### ISSUE THREAD

**Issue by djryan7** [sshnet/SSH.NET#797] opened 2021-03-12 23:35 UTC
Currently our companies Virus protection Framework from Microsoft is flagging all the Unit Test with the following Virus.

Ransom:MSIL/Hasadcrypt.A

What do I need to have this resolved?

Thank you,
David Ryan

**Comment by IgorMilavec** [comment] 2022-02-13 00:27
Duplicate of #737

**Closed as completed by IgorMilavec** 2022-02-13 00:27 UTC
