### ISSUE TITLE
SFTP WriteAllBytes Corrupt

### ISSUE THREAD

**Issue by rrs** [sshnet/SSH.NET#218] opened 2017-05-05 07:57 UTC
Hi,

I am uploading a csv file to sftp. The file ends up corrupted. 
After ~250 lines it reprints the column headers along with the first ~250 rows instead of the following ~250 rows then continues on with the rest of the file.

I have the same application deployed to multiple locations and only some locations exhibit this behavior. I log the output locally and can verify the output itself is correct.

Here is the upload code
```
var fileBytes = Encoding.UTF8.GetBytes(file);
var connectionInfo = new ConnectionInfo(_settings.FtpServer, _settings.FtpUserName, new PasswordAuthenticationMethod(_settings.FtpUserName, _settings.FtpPassword));
using (var client = new SftpClient(connectionInfo))
{
    client.Connect();
    client.WriteAllBytes($"{_settings.FtpPath}/{fileName}", fileBytes);
    CsvLogger.Info(file);
}
```

I have also tried using client.OpenWrite and .Write instead and still the same issue.

Any advice would be appreciated

Thanks

**Comment by kasbst** [comment] 2017-05-05 13:07
@rrs This is fixed in version 2016.1.0-beta1. It seems you are using version 2016.0.0 check #124 and #116

**Comment by BobLokerse** [comment] 2017-05-22 13:30
So, this issue can be closed?

**Closed as completed** 2017-05-22 13:37 UTC
Labels: duplicate

**Comment by drieseng** [comment] 2017-07-18 19:59
Duplicate of issue #70.

A new beta will be available soon, and final release shortly after.
