### ISSUE TITLE
SetLastWriteTime and SetLastWriteTimeUtc not implemented

### ISSUE THREAD

**Issue by ygoe** [sshnet/SSH.NET#228] opened 2017-05-30 14:51 UTC
This is documented in the code, these methods throw a NotImplementedException. I'd rather have them do what they're supposed to do. Is this a complicated feature to implement?

Or, put it another way, can I upload a local file and keep its last write time?

**Comment by ygoe** [comment] 2017-05-30 17:40
This code seems to be the workaround:

	var sftpFile = client.Get("path/to/file");
	sftpFile.LastWriteTimeUtc = someTime;
	sftpFile.UpdateStatus();

**Comment by Rondom** [comment] 2017-05-30 22:39
See #217

**Comment by ygoe** [comment] 2017-05-31 06:38
That doesn't help for the *Utc methods because the attributes don't have that information.

**Comment by drieseng** [comment] 2017-08-16 19:03
Duplicate of #217.

**Closed as completed by drieseng** 2017-08-16 19:03 UTC
Labels: duplicate

**Comment by WojciechNagorski** [comment] 2023-10-10 21:47
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
