### ISSUE TITLE
Binding SFTP Client to a single IP address

### ISSUE THREAD

**Issue by rmanoni** [sshnet/SSH.NET#236] opened 2017-06-19 22:43 UTC
Is is possible to bind the SftpClient to the source IP address?

I have a server with multiple IP addresses configured.  Can I setup the SFTP to bind to only one of those addresses, as the remote server I am ftp-ing to only allows a connection from one of the configured IPs?

Thank you for your time.

**Comment by IgorMilavec** [comment] 2022-02-12 23:02
Duplicate of #132

**Closed as completed by IgorMilavec** 2022-02-12 23:02 UTC
