### ISSUE TITLE
SftpFileStream.Write() corrupt PDF files

### ISSUE THREAD

**Issue by bgillet** [sshnet/SSH.NET#124] opened 2016-12-06 16:27 UTC
Hi !

I am using latest stable version of the library (2016.0.0).

When I use SftpClient.OpenWrite() method to create a file on SFTP server, I get an SftpFileStream where writing to.

When I write into this stream data from a valid PDF file, I get a "valid" PDF file on SFTP server. When I say "valid" it is not really true. PDF file has same size as original file and can be opened. But, in fact, the PDF file is not valid because images inside the document have been corrupted while text content is still correct.

Partial screenshot of original generated PDF :
![image](https://cloud.githubusercontent.com/assets/3019854/20933679/1e8da586-bbd9-11e6-8fc1-2e42e95b4156.png)

Partial screenshot of corrupted copied PDF :
![image](https://cloud.githubusercontent.com/assets/3019854/20933729/3b0bf622-bbd9-11e6-832c-f92e4706b98c.png)

Here is a comparaison of file content :
![image](https://cloud.githubusercontent.com/assets/3019854/20934016/1703fe9a-bbda-11e6-9c5c-59a7a9cb380d.png)

It looks like beginning of PDF is written again in destination file. It looks like a buffer problem.

Problem is solved when setting a buffer size (ex: 1024) to the stream's CopyTo() method.

**Comment by h7web** [comment] 2016-12-09 16:14
Do you know where a simple example of using this library might be found? I am new to this library and am not finding any documentation to tell me how to use it. Thanks!

**Comment by drieseng** [comment] 2016-12-14 20:23
This should be fixed in version **2016.1.0-beta1**.
Please test and provide feedback.

**Comment by BobLokerse** [comment] 2017-03-14 08:34
As in #116 , I can confirm that it fixed my similar problem.

Is there an expectation date when this fix will come out of beta?

**Comment by drieseng** [comment] 2017-07-18 19:57
Duplicate of issue #70.

A new beta will be available soon, and final release shortly after.

**Closed as completed by drieseng** 2017-07-18 19:57 UTC
Labels: duplicate
