### ISSUE TITLE
Bug in SftpFileStream.Write(byte[] buffer, int offset, int count) ?

### ISSUE THREAD

**Issue by guillaume86** [sshnet/SSH.NET#116] opened 2016-11-14 10:19 UTC
Hi,

I'm still investigating the issue so I could be wrong, but it's possible that since updating to 2016.0.0.0 from some 2014 version, SftpFileStream.Write has a bug that corrupt the destination file.

The created file has the correct length, but the content is the first 32.741 bytes of the buffer repeated till the correct file size is reached.

It's a pretty serious issue so I posted it as soon as I found out, I'm now investigating the issue in detail to confirm the problem.

**Comment by guillaume86** [comment] 2016-11-14 11:03
It's fixed in the source code (tried to build from source and test) but the current Nuget version contains the bug.
I would recommend blacklist that version (or whatever it's called in Nuget) and release an update as soon as possible, it's a pretty bad one IMO.

**Comment by drieseng** [comment] 2016-11-22 19:56
I'm gonna try to ship a new beta this weekend.

**Comment by drieseng** [comment] 2016-12-14 20:24
This should be fixed in version 2016.1.0-beta1.
Please test and provide feedback.

**Comment by sychare** [comment] 2017-01-23 15:31
I've just run into this issue with 2016.0 and can confirm that the 2016.1 beta appears to resolve it.

**Comment by BobLokerse** [comment] 2017-03-14 08:27
I can also confirm that it fixed my similar problem.

Is there an expectation date when this fix will come out of beta?

**Comment by drieseng** [comment] 2017-07-18 19:52
Duplicate of issue #70.

I'll be releasing a new beta soon.

**Closed as completed by drieseng** 2017-07-18 19:52 UTC
Labels: duplicate
