### ISSUE TITLE
WriteAllBytes don't work in 2016 version

### ISSUE THREAD

**Issue by roarjoss** [sshnet/SSH.NET#220] opened 2017-05-10 09:10 UTC
Hello,
I discovered an issue uploading files.
I upload a csv file with column headers.
What happens is that the column headers are repeated when the buffer size is reached.
Increasing the buffer size to larger than the pushes the problem further into the file but does not provide a workaround.
Reverting to the 2013 version of the library seems to provide a workaround.
So the bug was introduced after version 2013.4.7.0

Here is my code. The problem occurs around the 4k in the file, the column header at the start of the file is repated 4k into the file.
I verified that the problem is not in my data.
The problem occurs only when uploading.

public string UploadByteArray(string ftppath, byte[] databuffer)
		{
			using (var client = new SftpClient(HostName, UserName, Password))
			{
				client.Connect();
				Console.WriteLine("Connected to {0}", HostName);

				client.BufferSize = 4 * 1024;
				client.WriteAllBytes(ftppath, databuffer);
				client.Disconnect();
			}
			return null;
		}

**Comment by kasbst** [comment] 2017-05-10 10:09
@roarjoss : Did you try also version 2016.1.0-beta1? Check #124 #116 and #218

**Comment by BobLokerse** [comment] 2017-05-22 13:50
@roarjoss Did it work with version 2016.1.0-beta1?

Just waiting for the that version to come out of beta.

**Comment by roarjoss** [comment] 2017-05-22 14:17
When I both use 2016.1.0-beta1 and set buffer size to larger than filesize it worked.

I think there might still be some issue with 2016.1.0-beta1 if buffer size is smaller than file size.
A customer reported that the file file content was duplicated with 4k buffer and 300k file size, the file content was written twice. The first half was correct, the second half a duplicate of the first.
This only happens sometimes.

**Comment by drieseng** [comment] 2017-07-18 19:53
Duplicate of issue #70.

A new beta will be available soon, and final release shortly after.

**Closed as completed by drieseng** 2017-07-18 19:53 UTC
Labels: duplicate
