### ISSUE TITLE
Session operation has timed out with version 2023.0.0 ok with 2020.0.2

### ISSUE THREAD

**Issue by Foxsterc** [sshnet/SSH.NET#1260] opened 2023-12-07 17:46 UTC
Hi,

I get the following error with version 2023.0.0

`Session operation has timed out at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout) at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle) at Renci.SshNet.PrivateKeyAuthenticationMethod.Authenticate(Session session) at Renci.SshNet.AuthenticationMethod.Renci.SshNet.IAuthenticationMethod.Authenticate(ISession session) at Renci.SshNet.ClientAuthentication.TryAuthenticate(ISession session, AuthenticationState authenticationState, String[] allowedAuthenticationMethods, SshAuthenticationException& authenticationException) at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session) at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory) at Renci.SshNet.Session.Connect() at Renci.SshNet.BaseClient.CreateAndConnectSession() at Renci.SshNet.BaseClient.Connect() `

With the following code

`                var connectionInfo = new ConnectionInfo(this.Host,

                                this.Username,
                                new PrivateKeyAuthenticationMethod(this.Username, new[] { new PrivateKeyFile(this.PrivateKeyPath) }))
                {
                    RetryAttempts = 3,

                };

                using SftpClient client = new SftpClient(connectionInfo);

                client.Connect();
`

The same code works fine with version 2020.0.2

Thanks,

**Comment by Rob-Hague** [comment] 2023-12-08 17:41
Sorry to hear that. Does it happen every time, or sporadically?

There have been some issues reported here https://github.com/sshnet/SSH.NET/issues/1233#issuecomment-1804346396. It might be worth a try. (edit: on second thoughts, that is about authentication, not connection)

**Comment by Foxsterc** [comment] 2023-12-08 17:53
Happens every time, just time out. I have to revert at the minute as it's in production.

**Comment by Rob-Hague** [comment] 2023-12-08 18:03
If you are motivated to troubleshoot (understandable if not), the most definitive way would be to run a packet capture and observe differences between the old version and new. With Wireshark it's possible to filter on SSH packets https://wiki.wireshark.org/SSH.md

**Comment by Rob-Hague** [comment] 2023-12-28 20:56
@Foxsterc would be interested to know if you still have issues on the latest `develop` branch (after 2b53e462dd77fd41978e05a6dff475c999e7424e) or not

**Comment by AdalbertKhoolsaat** [comment] 2024-01-02 09:13
Would like to add that although I use a different setup, I'm experiencing the same issue after upgrading from 2020.0.2 to 2023.0.0.

Client setup similar to this:
```
var client = new SftpClient(myEndpoint, myPort, myUser, myPassword);

client.HostKeyReceived += (sender, e) =>
{
using SHA256 sha256Hasher = SHA256.Create();
var sha256Fingerprint = Convert.ToBase64String(sha256Hasher.ComputeHash(e.HostKey));
e.CanTrust = sha256Fingerprint == myKnownSshHostKeyFingerprint.Split(' ')[^1];
};
```

I now see a version 2023.0.1 got released a few days ago. Does that one contain a potential fix?

**Comment by Rob-Hague** [comment] 2024-01-02 10:57
@AdalbertKhoolsaat please try 2023.0.1 and report back, thanks

**Comment by WojciechNagorski** [comment] 2024-01-02 11:16
The 2023.0.1 version contains fixes that can help you. Please try new version.

**Comment by AdalbertKhoolsaat** [comment] 2024-01-02 11:32
Alright, I have upgraded to the latest version but with mixed results. Debugging locally on a Windows machine it works, but once deployed on AWS Lambda (i.e. Amazon Linux 2) the issues still persist, albeit with a somewhat different error:

```
Renci.SshNet.Common.SshOperationTimeoutException: Connection failed to establish within 30000 milliseconds.
   at Renci.SshNet.Abstractions.SocketAbstraction.ConnectCore(Socket socket, IPEndPoint remoteEndpoint, TimeSpan connectTimeout, Boolean ownsSocket)
   at Renci.SshNet.Connection.ConnectorBase.SocketConnect(String host, Int32 port, TimeSpan timeout)
   at Renci.SshNet.Connection.DirectConnector.Connect(IConnectionInfo connectionInfo)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   ...
   ..
   .

```

This setup worked without issues on 2020.0.2, so next attempt will be downgrading (for now).

**Comment by AdalbertKhoolsaat** [comment] 2024-01-02 14:42
> Alright, I have upgraded to the latest version but with mixed results. Debugging locally on a Windows machine it works, but once deployed on AWS Lambda (i.e. Amazon Linux 2) the issues still persist, albeit with a somewhat different error:
> 
> ```
> Renci.SshNet.Common.SshOperationTimeoutException: Connection failed to establish within 30000 milliseconds.
>    at Renci.SshNet.Abstractions.SocketAbstraction.ConnectCore(Socket socket, IPEndPoint remoteEndpoint, TimeSpan connectTimeout, Boolean ownsSocket)
>    at Renci.SshNet.Connection.ConnectorBase.SocketConnect(String host, Int32 port, TimeSpan timeout)
>    at Renci.SshNet.Connection.DirectConnector.Connect(IConnectionInfo connectionInfo)
>    at Renci.SshNet.Session.Connect()
>    at Renci.SshNet.BaseClient.CreateAndConnectSession()
>    at Renci.SshNet.BaseClient.Connect()
>    ...
>    ..
>    .
> ```
> 
> This setup worked without issues on 2020.0.2, so next attempt will be downgrading (for now).

Turns out this error was caused by additional changes related to our provisioning on AWS (specifically, the Lambda had been placed inside a VPC). When put outside the VPC everything works as expected again using version 2023.0.1.

**Comment by Rob-Hague** [comment] 2024-01-02 20:18
Glad you got it sorted

@Foxsterc I will close this one for now, but if you still see the same issue on 2023.0.1 feel free to re-open

**Closed as completed by Rob-Hague** 2024-01-02 20:18 UTC

**Comment by Foxsterc** [comment] 2024-01-04 13:18
Apologies @Rob-Hague I've been away. I'm not in a position to test it ay the moment but I will try it as soon as I can.
