### ISSUE TITLE
Problem with SOCKS5 proxy

### ISSUE THREAD

**Issue by tfontS2G** [sshnet/SSH.NET#417] opened 2018-04-06 07:32 UTC
Hello,

I'm trying to connect to an SFTP server through SOCKS5 proxy. When I try to connect I get: "SOCKS5: General Failure" exception. I'm importing directly the "Renci.SshNet.dll" as a reference into my project. 

Any ideas about what is the problem?

**Comment by tfontS2G** [comment] 2018-04-06 07:34
The code:


`namespace SFTP
{
    class Program
    {
        static void Main(string[] args)
        {
            string username = "****";
            string password = "****";
            string host = "****";
            int port = 22222;

            string proxy_Host = @"****";
            string proxy_Username = @"****";
            string proxy_Password = "****";
            int proxy_Port = 1080;

            AuthenticationMethod authMethod = new PasswordAuthenticationMethod(username, password);

            ConnectionInfo sftpConnection = new ConnectionInfo(host, port, username, ProxyTypes.Socks5, proxy_Host, proxy_Port, proxy_Username, proxy_Password, authMethod);

            SftpClient client = new SftpClient(sftpConnection);

            try
            {
                client.Connect();
                

                Console.WriteLine("Connection established!");
                Console.ReadKey();
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.ToString());
                Console.ReadKey();
            }
        }
    }
}`

**Comment by drieseng** [comment] 2020-06-27 14:05
This is probably a duplicate of https://github.com/sshnet/SSH.NET/pull/125, which was fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).

**Closed as completed by drieseng** 2020-06-27 14:05 UTC
