### ISSUE TITLE
Flagged as Malware by AV

### ISSUE THREAD

**Issue by slcraft** [sshnet/SSH.NET#887] opened 2021-10-10 19:01 UTC
Installed SSH.NET 2020.0.1 as a nuget package in a clean Visual Studio C# project, and ran the following code - which immediately triggered multiple AntiVirus notifications which ended up quarantining the application.  

```
SftpClient sftp = new SftpClient("hostname", "user", new PrivateKeyFile(@"C:\Path\to\id_rsa"));
sftp.Connect();
```

The cited threat from AV was that it was acting like: not-a-virus:PDM:AdWare.NSIS.ConvertAd.bCb.

**Comment by IgorMilavec** [comment] 2021-11-12 17:09
Should be fixed by #867

**Comment by IgorMilavec** [comment] 2022-02-13 00:25
Duplicate of #797

**Closed as completed by IgorMilavec** 2022-02-13 00:25 UTC
