### ISSUE TITLE
Session Operation Timeout Exception after 'KeyExchangeDhGroupExchangeInit' step

### ISSUE THREAD

**Issue by lchengNetBall** [sshnet/SSH.NET#384] opened 2018-02-13 02:10 UTC
Hi,

I am using  2016.1.0 version of SSH.NET. Sometime I got "Session Operation Timeout" exception after
"KeyExchangeDhGroupExchangeInit" step.

This is the trace log from debug dll.

Can you please help me out on this issue?

SshNet.Logging Verbose: 1 : Initiating connection to 'xxx'.
SshNet.Logging Verbose: 1 : Server version '2.0' on 'GoAnywhere5.2.5'.
SshNet.Logging Verbose: 7 : [] Received message 'KeyExchangeInitMessage' from server: 'SSH_MSG_KEXINIT'.
SshNet.Logging Verbose: 7 : [] Sending message 'KeyExchangeInitMessage' to server: 'SSH_MSG_KEXINIT'.
SshNet.Logging Verbose: 7 : [] Sending message 'KeyExchangeDhGroupExchangeRequest' to server: 'SSH_MSG_KEX_DH_GEX_REQUEST'.
SshNet.Logging Verbose: 7 : [] Received message 'KeyExchangeDhGroupExchangeGroup' from server: 'SSH_MSG_KEX_DH_GEX_GROUP'.
SshNet.Logging Verbose: 7 : [] Sending message 'KeyExchangeDhGroupExchangeInit' to server: 'SSH_MSG_KEX_DH_GEX_INIT'.
The thread 0x7488 has exited with code 0 (0x0).
Exception thrown: 'Renci.SshNet.Common.SshOperationTimeoutException' in Renci.SshNet.dll
SshNet.Logging Verbose: 1 : Disposing client.
SshNet.Logging Verbose: 1 : Disconnecting client.
SshNet.Logging Verbose: 1 : [] Disposing session.
SshNet.Logging Verbose: 1 : [] Disconnecting session.
SshNet.Logging Verbose: 1 : [] Shutting down socket.
SshNet.Logging Verbose: 1 : [] Disposing socket.
SshNet.Logging Verbose: 1 : [] Disposed socket.
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in Renci.SshNet.dll
SshNet.Logging Verbose: 7 : [] Raised exception: Renci.SshNet.Common.SshConnectionException: A blocking operation was interrupted by a call to WSACancelBlockingCall ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) in C:\Projects\ASH\trunk\Dependencies\ssh.net 2016.1.0\SSH.NET-2016.1.0\src\Renci.SshNet\Abstractions\SocketAbstraction.cs:line 328
   at Renci.SshNet.Session.TrySocketRead(Byte[] buffer, Int32 offset, Int32 length) in C:\Projects\ASH\trunk\Dependencies\ssh.net 2016.1.0\SSH.NET-2016.1.0\src\Renci.SshNet\Session.cs:line 1744
   at Renci.SshNet.Session.ReceiveMessage() in C:\Projects\ASH\trunk\Dependencies\ssh.net 2016.1.0\SSH.NET-2016.1.0\src\Renci.SshNet\Session.cs:line 1050
   at Renci.SshNet.Session.MessageListener() in C:\Projects\ASH\trunk\Dependencies\ssh.net 2016.1.0\SSH.NET-2016.1.0\src\Renci.SshNet\Session.cs:line 1892
   --- End of inner exception stack trace ---
The thread 0x1828 has exited with code 0 (0x0).

Regards
Li

**Comment by drieseng** [comment] 2020-06-28 07:38
This is a duplicate of https://github.com/sshnet/SSH.NET/issues/304, which was fixed in [2016.1.0](https://github.com/sshnet/SSH.NET/releases/tag/2016.1.0).

**Closed as completed by drieseng** 2020-06-28 07:38 UTC
