### ISSUE TITLE
SshClient.Dispose is throwing exception when SSH session gets disconnected unexpectedely

### ISSUE THREAD

**Issue by mauroa** [sshnet/SSH.NET#96] opened 2016-10-03 19:37 UTC
The disposal of an SshClient instance could end throwing an exception when the SSH Session gets disconnected by the remote host.

A quick look into the code shows that even if the Dispose methods calls Disconnect internally and doesn't have exception handling (https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/BaseClient.cs#L339) , there is always a null check over the SshSession (https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/BaseClient.cs#L225-L246) to prevent any unwanted NullReferenceException. However, something is still going on when the session is remotely disconnected and the SshClient is tried to be disposed after that.

**Comment by drieseng** [comment] 2016-10-06 19:27
This should be fixed in the **develop** branch.
What version of **SSH.NET** are you using, and can you _easily_ reproduce this issue?
Would it be possible for you to build **SSH.NET** from source?
If not, I can send you an assembly built from source.
Just let me know which framework you're targeting.

**Comment by icnocop** [comment] 2016-10-28 23:30
@drieseng , Can we utilize the CI appveyor build so that it automatically publishes the output whenever the code changes so that it can be downloaded and used with less effort?

For example, the build can publish the nuget package to any one of these repositories:
1. To nuget and indicate that it's a prerelease build (recommended)
2. To the appveyor project as a build artifact
    Is this already happening? If so, can you provide a link please?
3. To this github project as a "release", but probably indicate that's it's not "official"

Thank you! :)

**Comment by Austneal** [comment] 2016-11-18 18:37
Is there a workaround for this, or do we still need to build from the development branch?

**Comment by drieseng** [comment] 2016-11-22 19:57
I'm gonna try to ship a new beta this weekend.

**Comment by josephearl** [comment] 2016-12-06 14:14
Experiencing this issue on 2016.0, a fix would be great 👍

**Comment by drieseng** [comment] 2016-12-14 20:38
This should be fixed in version 2016.1.0-beta1.
Please test and provide feedback.

**Comment by josephearl** [comment] 2016-12-15 16:22
Thanks!

**Comment by drieseng** [comment] 2017-02-19 14:52
@JosephEarl Can you confirm that this issue is fixed in **2016.1.0-beta1**?

**Comment by josephearl** [comment] 2017-02-19 22:34
@drieseng yes works for me

**Closed as completed** 2017-02-20 16:19 UTC
Labels: bug

**Comment by ogborstad** [comment] 2017-06-15 12:27
Does this release get out of beta soon?
